hunav_loader:
  ros__parameters:
    map: default
    publish_people: true
    agents:
      - person1
      - person2
    person1:
      id: 1
      skin: 0
      group_id: -1
      max_vel: 0.5
      radius: 0.4
      behavior:
        type: 2
        configuration: 1
        duration: 40.0
        once: true
        vel: 1.0
        dist: 4.5
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 1.0
        other_force_factor: 20.0
      init_pose:
        x: -6.976060
        y: 8.873902
        z: 1.250000
        h: 1.0
      goal_radius: 0.3
      cyclic_goals: false
      goals: ["g0"]
      g0:
        x: -6.976060
        y: 8.873902
        h: 1.0
    person2:
      id: 2
      skin: 1
      group_id: -1
      max_vel: 0.5
      radius: 0.4
      behavior:
        type: 2
        configuration: 1
        duration: 40.0
        once: true
        vel: 1.0
        dist: 4.5
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 0.0
        other_force_factor: 20.0
      init_pose:
        x: -5.976060
        y: 9.873902
        z: 1.250000
        h: 1.0
      goal_radius: 0.3
      cyclic_goals: false
      goals: ["g0"]
      g0:
        x: -5.976060
        y: 9.873902
        h: 1.0
